apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: greeter
          image: example.com/tekton-tutorial/helloworld
          resources:
            limits:
              memory: '500m'
              cpu: '1'
          ports:
            - containerPort: 8080
